const CACHE = 'focusai-adc66834b5';
const FILES = [
  './',
  './index.html',
  './css/a11y-focus-visible.css',
  './css/a11y-reduced-motion.css',
  './css/add-friend-modal.css',
  './css/app-login-gate.css',
  './css/app-shell-layout.css',
  './css/arena.css',
  './css/asama-duzeltmeleri.css',
  './css/book-premium-tooltip.css',
  './css/bsi-stat-cards.css',
  './css/buddy-habit.css',
  './css/bugun-minimalist.css',
  './css/bugun-tasarim-v2.css',
  './css/bugun-td-add-form-fixes.css',
  './css/bugun-yeni-minimal-tasarim.css',
  './css/calendar-day-drawer.css',
  './css/calendar-dnd-preview.css',
  './css/calendar-dragdrop-cards.css',
  './css/calendar-edit-chip-height.css',
  './css/calendar-event-cards.css',
  './css/calendar-fullscreen-mode.css',
  './css/calendar-gcal-style-chip.css',
  './css/calendar-habit-dump-widgets.css',
  './css/calendar-header-event-modal.css',
  './css/calendar-highlight-drag.css',
  './css/calendar-highlight-timeline.css',
  './css/calendar-hover-popup.css',
  './css/calendar-tab-bridge-override.css',
  './css/calendar-week-day-view.css',
  './css/chat-confirm-modal.css',
  './css/chat-fab-drag-room-pills.css',
  './css/chat-misc-widgets.css',
  './css/chat-reply-bar.css',
  './css/chat-theme-wallpaper-picker.css',
  './css/collab-invite-modal.css',
  './css/collab-plan-invite-card.css',
  './css/command-palette.css',
  './css/core-modal-system-bridge-v2.css',
  './css/core-modal-system.css',
  './css/core-utilities.css',
  './css/deepwrite-editor.css',
  './css/faz2-layout-overrides.css',
  './css/faz3-render-bridge-override.css',
  './css/faz5-istatistik-gunluk-bridge.css',
  './css/faz7-social-dock-cleanup.css',
  './css/five-modal-shared-polish.css',
  './css/flatpickr-theme.css',
  './css/focus-mode-page-shell.css',
  './css/focusai-confirm-modal.css',
  './css/goal-card-detail.css',
  './css/goal-detail-item-templates.css',
  './css/goal-detail-modal-sizing.css',
  './css/goal-modal-custom.css',
  './css/goal-section-header-minimal.css',
  './css/group-focus-room-friends.css',
  './css/group-focus-session-cws.css',
  './css/group-focus-session.css',
  './css/groups-discover.css',
  './css/groups-hub-panel.css',
  './css/gun-serisi-alev-sistemi.css',
  './css/habit-create-modal-padding.css',
  './css/habit-modal-fields.css',
  './css/habit-tracker.css',
  './css/help-center.css',
  './css/hero-metric-stats.css',
  './css/hybrid-chat-ui.css',
  './css/inline-quick-add-popup.css',
  './css/leaderboard.css',
  './css/library-bookshelf-visuals.css',
  './css/library-bookshelf.css',
  './css/mgmt-member-rows.css',
  './css/mind-dump.css',
  './css/mini-profile-popup.css',
  './css/misc-small-widgets.css',
  './css/native-time-picker.css',
  './css/onboarding-tour.css',
  './css/page-scroll-zoom-fix.css',
  './css/planning-collab-live-features.css',
  './css/planning-collab-panel.css',
  './css/planning-collab-wait.css',
  './css/planning-ghost-toast.css',
  './css/planning-lesson-plan-assign-modal.css',
  './css/planning-lesson-plan-invites.css',
  './css/planning-lesson-plan-modal.css',
  './css/planning-main-page-layout.css',
  './css/planning-milestone-widgets.css',
  './css/planning-misc-widgets.css',
  './css/planning-mode-select-modal.css',
  './css/planning-plan-view-milestone-wizard.css',
  './css/planning-quick-create.css',
  './css/planning-subtask-list.css',
  './css/planning-wizard-lesson-plan.css',
  './css/poll-card.css',
  './css/premium-ambient-misc-widgets.css',
  './css/premium-validation-minddump-drawer.css',
  './css/profile-dropdown-menu.css',
  './css/profile-edit-modal.css',
  './css/profile-settings-modal.css',
  './css/room-presence-strip.css',
  './css/sidebar-chat-panel-redesign.css',
  './css/sidebar-social-panel-redesign.css',
  './css/social-color-toast.css',
  './css/social-group-roles-permissions.css',
  './css/social-institution-panel.css',
  './css/social-online-friends.css',
  './css/social-productivity-share.css',
  './css/sohbet-3sutun-mimari.css',
  './css/sohbet-faz-gelistirmeleri.css',
  './css/sohbet-sol-panel-final.css',
  './css/sohbet-tab-design-v2.css',
  './css/sohbet-tab-minimalist.css',
  './css/statistics-page.css',
  './css/style-final-overrides.css',
  './css/style.css',
  './css/system-settings-modal.css',
  './css/task-card-themes-scrollbar.css',
  './css/task-form-misc-controls.css',
  './css/task-mini-goal-selector.css',
  './css/time-picker-task-controls.css',
  './css/timer-ambient-mixer.css',
  './css/timer-bridge-override.css',
  './css/timer-core-widget.css',
  './css/timer-floating-widgets.css',
  './css/timer-profiles.css',
  './css/timer-scene-immersive-mode.css',
  './css/timer-scene-picker.css',
  './css/timer-settings-advanced.css',
  './css/timer-task-end-question.css',
  './css/today-sprint-widget.css',
  './css/tokens.css',
  './css/trend-chart-svg.css',
  './css/undo-toast-fab-spotlight.css',
  './css/utility-classes.css',
  './css/v2-design-system.css',
  './css/zettelkasten-library.css',
  './inline-a11y-patch.js',
  './inline-button-failsafe.js',
  './inline-dock-topbar-init.js',
  './inline-error-net.js',
  './inline-goal-modal-globals.js',
  './inline-onclick-migration.js',
  './inline-sw-register.js',
  './inline-tab-restore-dom.js',
  './inline-tab-restore-early.js',
  './js/app-login-gate.js',
  './js/auth-ui-utils.js',
  './js/auth-ui.js',
  './js/collab-utils.js',
  './js/collab.js',
  './js/inline-gate-prehide.js',
  './js/inline-module-loader.js',
  './js/planning-collab-handlers.js',
  './js/planning-collab-invite-delete.js',
  './js/planning-collab-wait.js',
  './js/planning-day-panel-events.js',
  './js/planning-day-panel-markup.js',
  './js/planning-dependency-graph.js',
  './js/planning-detail-panel.js',
  './js/planning-ghost-toast.js',
  './js/planning-goal-collab-bridge.js',
  './js/planning-goal-crud.js',
  './js/planning-goal-detail-render.js',
  './js/planning-goal-load-sync.js',
  './js/planning-goal-sync-cleanup.js',
  './js/planning-hourgrid-render.js',
  './js/planning-init-setup.js',
  './js/planning-lesson-plan-assign-status-html.js',
  './js/planning-lesson-plan-assign.js',
  './js/planning-lesson-plan-busy-slots.js',
  './js/planning-lesson-plan-conflicts.js',
  './js/planning-lesson-plan-invites.js',
  './js/planning-lesson-plan-mirror.js',
  './js/planning-lesson-plan-modal.js',
  './js/planning-lesson-plan-route.js',
  './js/planning-main-cal-render.js',
  './js/planning-milestone-crud.js',
  './js/planning-milestone-list-render.js',
  './js/planning-milestone-wizard-cal.js',
  './js/planning-milestone-wizard-collab-invite.js',
  './js/planning-milestone-wizard-step1-form.js',
  './js/planning-milestone-wizard-step2-count.js',
  './js/planning-milestone-wizard-step3-render.js',
  './js/planning-milestone-wizard-step5-save.js',
  './js/planning-milestone-wizard-task-render.js',
  './js/planning-milestone-wizard.js',
  './js/planning-misc-widgets-templates.js',
  './js/planning-misc-widgets.js',
  './js/planning-open-plan-view.js',
  './js/planning-plan-header.js',
  './js/planning-plan-summary-render.js',
  './js/planning-plan-view-dom-fx.js',
  './js/planning-plan-view-exit.js',
  './js/planning-plan-view-time-utils.js',
  './js/planning-pv-lifecycle.js',
  './js/planning-pv-main-cal.js',
  './js/planning-pv-render.js',
  './js/planning-quick-add-ms.js',
  './js/planning-quick-create-collab.js',
  './js/planning-quick-create.js',
  './js/planning-realtime.js',
  './js/planning-toast-esc.js',
  './js/planning-utils.js',
  './js/planning-week-day-cal-render.js',
  './js/planning-wizard-date-utils.js',
  './js/planning-wizard-info-tooltip.js',
  './js/planning-wizard.js',
  './js/planning.js',
  './js/script-add-task.js',
  './js/script-ambient-sounds.js',
  './js/script-book-detail-modal.js',
  './js/script-cal-dnd.js',
  './js/script-calendar-date-utils.js',
  './js/script-calendar-dragdrop.js',
  './js/script-calendar-fullscreen.js',
  './js/script-calendar-hover-popup.js',
  './js/script-calendar-month-view-event-html.js',
  './js/script-calendar-month-view.js',
  './js/script-calendar-sync-bridge.js',
  './js/script-calendar-view-switch.js',
  './js/script-calendar-week-day-view-drag-ghost.js',
  './js/script-calendar-week-day-view-move-task.js',
  './js/script-calendar-week-day-view.js',
  './js/script-challenge-days.js',
  './js/script-color-utils.js',
  './js/script-command-palette.js',
  './js/script-confetti.js',
  './js/script-convert-modal.js',
  './js/script-coworking-groups.js',
  './js/script-daily-highlight.js',
  './js/script-data-sync-refresh.js',
  './js/script-date-time-utils.js',
  './js/script-day-drawer-core.js',
  './js/script-day-drawer-render.js',
  './js/script-day-summary-card.js',
  './js/script-edit-task-modal.js',
  './js/script-evening-reflection-modal.js',
  './js/script-event-modal.js',
  './js/script-focus-mode.js',
  './js/script-goal-archiver.js',
  './js/script-goal-deadline-extend.js',
  './js/script-goal-delete-prompt.js',
  './js/script-goal-details-panel.js',
  './js/script-goal-details-sections.js',
  './js/script-goal-modal-analysis.js',
  './js/script-goal-modal-cards.js',
  './js/script-goal-modal-list-utils.js',
  './js/script-goal-modal-open-close.js',
  './js/script-goal-modal.js',
  './js/script-goal-reward-ui.js',
  './js/script-habit-category-modal.js',
  './js/script-habit-edit-modal.js',
  './js/script-habit-goal-synergy.js',
  './js/script-habit-modal-dates.js',
  './js/script-habit-render-mutate.js',
  './js/script-habit-sync.js',
  './js/script-journal-library-book-detail.js',
  './js/script-journal-library-deepwrite.js',
  './js/script-journal-library-month-modal.js',
  './js/script-journal-library.js',
  './js/script-journal-modal.js',
  './js/script-library-lamp-parallax.js',
  './js/script-migrate-event-keys.js',
  './js/script-milestone-auto-splitter.js',
  './js/script-milestone-goal-actions.js',
  './js/script-mind-dump-calendar-bridge.js',
  './js/script-mind-dump-drawer.js',
  './js/script-mind-dump-tag-meta.js',
  './js/script-mind-dump-time-utils.js',
  './js/script-mind-dump.js',
  './js/script-misc-widgets.js',
  './js/script-move-task-to-date.js',
  './js/script-nlp.js',
  './js/script-onboarding-tour-flows.js',
  './js/script-onboarding-tour-progress-storage.js',
  './js/script-onboarding-tour.js',
  './js/script-plan-wizard.js',
  './js/script-populate-parent-selects.js',
  './js/script-premium-alert-toast.js',
  './js/script-premium-modal.js',
  './js/script-profile-dropdown.js',
  './js/script-profile-edit.js',
  './js/script-quick-add.js',
  './js/script-reflection-date-utils.js',
  './js/script-render-social-stats.js',
  './js/script-schedule-conflict-utils.js',
  './js/script-settings-steppers.js',
  './js/script-smart-task-add.js',
  './js/script-spotlight-search.js',
  './js/script-statistics-heatmap.js',
  './js/script-statistics-productivity-score.js',
  './js/script-statistics-streak-averages.js',
  './js/script-statistics-trend-chart.js',
  './js/script-statistics.js',
  './js/script-system-settings.js',
  './js/script-tab-restore.js',
  './js/script-tab-switch-core.js',
  './js/script-task-breadcrumb.js',
  './js/script-task-complete-sound.js',
  './js/script-task-end-question.js',
  './js/script-task-render-mutate-item-builder.js',
  './js/script-task-render-mutate-today-rows.js',
  './js/script-task-render-mutate.js',
  './js/script-time-picker.js',
  './js/script-timer-alarm-sound.js',
  './js/script-timer-flame.js',
  './js/script-timer-mode-color.js',
  './js/script-timer.js',
  './js/script-today-stats.js',
  './js/script-toggle-activity-reaction.js',
  './js/script-toggle-task.js',
  './js/script-undo-toast.js',
  './js/script-update-timer-dropdown.js',
  './js/script.js',
  './js/social-activity-feed.js',
  './js/social-arena-chips.js',
  './js/social-assignments-badge.js',
  './js/social-auth-bootstrap.js',
  './js/social-avatar-utils.js',
  './js/social-block-users.js',
  './js/social-buddy-focus-settings-modal.js',
  './js/social-buddy-habits-notifications.js',
  './js/social-buddy-habits-pure-utils.js',
  './js/social-buddy-habits.js',
  './js/social-chat-clear.js',
  './js/social-chat-extras-file-upload.js',
  './js/social-chat-extras-notif-prefs.js',
  './js/social-chat-extras.js',
  './js/social-chat-gate.js',
  './js/social-chat-list-actions.js',
  './js/social-chat-local-delete.js',
  './js/social-chat-panel-open.js',
  './js/social-chat-search.js',
  './js/social-conn-status.js',
  './js/social-cw-control-request.js',
  './js/social-cw-heartbeat.js',
  './js/social-cw-invites.js',
  './js/social-cw-room-helpers.js',
  './js/social-daily-race.js',
  './js/social-dc-chat-context.js',
  './js/social-dc-chat-theme-constants.js',
  './js/social-dc-chat-theme.js',
  './js/social-dc-confirm-toasts.js',
  './js/social-dc-contacts.js',
  './js/social-dc-draft.js',
  './js/social-dc-group-admin.js',
  './js/social-dc-init.js',
  './js/social-dc-last-open-storage.js',
  './js/social-dc-mentions.js',
  './js/social-dc-message-cards.js',
  './js/social-dc-message-mutate.js',
  './js/social-dc-message-render.js',
  './js/social-dc-msg-dom-helpers.js',
  './js/social-dc-msg-selection.js',
  './js/social-dc-online-status.js',
  './js/social-dc-open-room.js',
  './js/social-dc-pagination.js',
  './js/social-dc-panel-view.js',
  './js/social-dc-profile-menu.js',
  './js/social-dc-profile-resolve.js',
  './js/social-dc-reply-reactions.js',
  './js/social-dc-room-lifecycle-teardown.js',
  './js/social-dc-room-lifecycle.js',
  './js/social-dc-scroll-skeleton.js',
  './js/social-dc-scroll-utils.js',
  './js/social-dc-session-strip.js',
  './js/social-dm-limit-notice.js',
  './js/social-dm-notifications-context-menu.js',
  './js/social-dm-notifications-toasts.js',
  './js/social-dm-notifications.js',
  './js/social-e2e.js',
  './js/social-emoji-picker.js',
  './js/social-floating-chat-badge.js',
  './js/social-focus-hush.js',
  './js/social-focus-quote-rotation.js',
  './js/social-focus-reminders.js',
  './js/social-friend-search.js',
  './js/social-friends-groups-listeners.js',
  './js/social-friends-notifications-dispatch.js',
  './js/social-friends-notifications-item-html.js',
  './js/social-friends-notifications-leaderboard-render.js',
  './js/social-friends-notifications-panel-events.js',
  './js/social-friends-notifications.js',
  './js/social-gamification-tournament.js',
  './js/social-gamification.js',
  './js/social-group-details-leaderboard.js',
  './js/social-group-details.js',
  './js/social-group-discover-category-labels.js',
  './js/social-group-discover-snapshot-adapter.js',
  './js/social-group-discover.js',
  './js/social-group-focus-break-chat.js',
  './js/social-group-focus-idle.js',
  './js/social-group-focus-leave.js',
  './js/social-group-focus-render.js',
  './js/social-group-focus-task-selector.js',
  './js/social-group-listeners.js',
  './js/social-group-mention-notif.js',
  './js/social-group-modal-setup.js',
  './js/social-group-session-calendar-date-utils.js',
  './js/social-group-session-calendar-theme.js',
  './js/social-group-session-calendar.js',
  './js/social-groups-pure-utils.js',
  './js/social-groups.js',
  './js/social-home-summary.js',
  './js/social-institution-class-modals-roster-patch.js',
  './js/social-institution-class-modals.js',
  './js/social-institution-classroom-insights-data.js',
  './js/social-institution-classroom-insights.js',
  './js/social-institution-classroom-perf-utils.js',
  './js/social-institution-classroom-sections-report.js',
  './js/social-institution-classroom-sections.js',
  './js/social-institution-classroom-wire-assignments.js',
  './js/social-institution-classroom-wire-performance.js',
  './js/social-institution-classroom-wire-schedule-roster.js',
  './js/social-institution-classroom-wire.js',
  './js/social-institution-my-groups-institution-modal.js',
  './js/social-institution-my-groups-invite-modal.js',
  './js/social-institution-my-groups.js',
  './js/social-institution-panel-shortcuts-widget.js',
  './js/social-institution-panel.js',
  './js/social-institution-student-report.js',
  './js/social-message-pins.js',
  './js/social-mini-focus-timer.js',
  './js/social-mini-profile-popup.js',
  './js/social-misc-isolated-utils.js',
  './js/social-misc-pure-utils.js',
  './js/social-my-groups-active.js',
  './js/social-notif-sounds.js',
  './js/social-online-friends.js',
  './js/social-online-people-popover.js',
  './js/social-polls.js',
  './js/social-presence-focus-utils.js',
  './js/social-presence.js',
  './js/social-productivity-share.js',
  './js/social-profile-header.js',
  './js/social-roles-pure-utils.js',
  './js/social-roles.js',
  './js/social-room-presence.js',
  './js/social-server-tree-context-menu.js',
  './js/social-server-tree.js',
  './js/social-settings-modal.js',
  './js/social-setup-modal-edit.js',
  './js/social-setup-profile-listeners.js',
  './js/social-shared-focus-math.js',
  './js/social-shared-focus-overlay-role-ui.js',
  './js/social-shared-focus-overlay-solo-room.js',
  './js/social-shared-focus-overlay.js',
  './js/social-shared-focus-phase-ui.js',
  './js/social-shared-focus-room-lifecycle.js',
  './js/social-shared-focus-sync.js',
  './js/social-shared-focus-timer-ctrl.js',
  './js/social-shared-focus-ui.js',
  './js/social-sidebar-profile.js',
  './js/social-throttle-and-date-utils.js',
  './js/social-toast.js',
  './js/social-typing-read-receipts.js',
  './js/social-unread-divider.js',
  './js/social-user-registration.js',
  './js/social.js',
  './js/state-store.js',
  './js/storage-manager.js',
  './js/supabase-client-row-converters.js',
  './js/supabase-client.js'
];

self.addEventListener('install', e => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(async c => {
      // c.addAll(FILES) YERİNE tek tek fetch+put: FILES artık build-time
      // otomatik üretiliyor (scripts/update-sw-file-list.py) ve 270+ dosya
      // içeriyor — addAll TÜM-YA-DA-HİÇBİRİ çalışır, listede tek bir eksik
      // dosya olsa (ör. üretim build'inde dosya adları hash'lenip
      // değiştiğinde) kurulumun TAMAMI sessizce başarısız olurdu.
      // Ayrıca bazı sunucular (SPA fallback yapan static host'lar, `vite
      // preview` dahil) olmayan bir yol için 404 yerine index.html'i 200
      // ile döndürür — content-type kontrolü olmadan bu, bir .css/.js
      // isteğinin YANLIŞLIKLA index.html içeriğiyle önbelleğe düşmesine
      // (ve offline modda sayfanın bozuk görünmesine) yol açar.
      await Promise.all(FILES.map(async url => {
        try {
          const res = await fetch(url, { cache: 'no-cache' });
          if (!res.ok) return; // 404 vb. — bu dosyayı sessizce atla, diğerlerini engelleme
          const ct = res.headers.get('content-type') || '';
          if (url.endsWith('.css') && !ct.includes('css')) return;
          if (url.endsWith('.js') && !ct.includes('javascript')) return;
          await c.put(url, res);
        } catch (_) { /* tek dosyanın ağ hatası diğerlerini engellemesin */ }
      }));
    })
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  // .js, .css, .html ve sayfa navigasyonları: stale-while-revalidate.
  // Önceki sürüm ("her zaman ağdan bekle") her yüklemede 4.6MB'lık ham JS/CSS'i
  // yeniden indirtiyordu — PWA'nın hız avantajını tamamen sıfırlıyordu. Bu
  // sürüm önbellekte varsa ANINDA onu döndürür (hızlı ilk boyama), AYNI ANDA
  // arka planda ağdan taze kopyayı çekip önbelleği günceller — bir sonraki
  // yüklemede yeni sürüm görünür. "Bayat veri asla güncellenmez" bug'ı
  // (2026-07-14) burada oluşmuyor çünkü her istekte arka plan revalidasyonu
  // tetikleniyor, cache asla "sonsuza dek dondurulmuş" olmuyor.
  const url = e.request.url;
  if (e.request.mode === 'navigate' || url.endsWith('.js') || url.endsWith('.css') || url.endsWith('.html')) {
    e.respondWith(
      caches.open(CACHE).then(async c => {
        const cached = await c.match(e.request);
        const network = fetch(e.request).then(res => {
          if (res && res.ok) c.put(e.request, res.clone());
          return res;
        }).catch(() => null);
        if (cached) {
          network; // arka planda güncelle, yanıtı bekletme
          return cached;
        }
        const fresh = await network;
        return fresh || cached || Response.error();
      })
    );
    return;
  }
  // Cross-origin istekleri (Supabase REST/Auth/Realtime, avatar/CDN vb.) HİÇ
  // önbelleğe alma. Aşağıdaki cache-first strateji buraya da uygulanıyordu —
  // aynı sorgu URL'si (ör. group_members select?group_id=eq.X) ilk yüklemede
  // önbelleğe yazılıp bir daha ASLA güncellenmiyordu (bu cache'in süresi/
  // geçersiz kılma mantığı yok). Sonuç: şube ataması gibi gerçek DB
  // güncellemeleri veritabanında doğru şekilde kalıcı oluyordu ama sayfa
  // yenilenince tarayıcı hep İLK YÜKLEMEDEKİ bayat API yanıtını görüyordu —
  // hem "şube ataması sayfa yenilenince gidiyor" hem de grup/panel restore
  // akışının bayat veriyle çalışıp Arena'ya düşmesi buradan kaynaklanıyordu
  // (2026-07-14). Cross-origin isteklerde respondWith çağırmayıp tarayıcının
  // normal ağ isteğini yapmasına izin veriyoruz.
  if (url.startsWith(self.location.origin)) {
    e.respondWith(
      caches.match(e.request).then(cached => cached || fetch(e.request))
    );
  }
});
// 4.3 — Push Notification handler
self.addEventListener('push', e => {
  let data = { title: 'FocusAI', body: 'Yeni bildirim', icon: './icon-192.png', tag: 'focusai' };
  try { if (e.data) data = { ...data, ...e.data.json() }; } catch(_) {}
  e.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body, icon: data.icon || './icon-192.png',
      badge: './icon-192.png', tag: data.tag || 'focusai',
      data: { url: data.url || '/' },
    })
  );
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  const url = e.notification.data?.url || '/';
  e.waitUntil(clients.matchAll({ type:'window' }).then(list => {
    const w = list.find(c => c.url === url && 'focus' in c);
    return w ? w.focus() : clients.openWindow(url);
  }));
});
